#### Fundamentals of Machine learning Engineering < Inspirration for this lecture was gotten from Daniel Bouke >

In [2]:
# Import PyTorch
import torch

### Creating a tensor

To create a tensor in Pytorch we use torch.tensor

In [2]:
# Scalars: A single number
scalar = torch.tensor(5)
print(scalar)

tensor(5)


In [3]:
print(scalar.shape)

torch.Size([])


In [4]:
# Vectors: 1-D tensor (array of numbers)
vector = torch.tensor([1, 2, 3, 4])
print(vector)

tensor([1, 2, 3, 4])


In [5]:
print(vector.shape)

torch.Size([4])


### Demonstrating the effect of Dimention on Tensors

In [29]:
# Tensor
TENSOR = torch.tensor([[1,2,3],[3,4,8]])
TENSOR

tensor([[1, 2, 3],
        [3, 4, 8]])

In [30]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([2, 3])

In [8]:
# Matrices: 2-D tensor (table of numbers)
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(MATRIX)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [9]:
MATRIX.shape

torch.Size([3, 3])

In [8]:
# Tensors: A generalization of matrices to higher dimensions
TENSOR_3D = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(TENSOR_3D)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [9]:
print(TENSOR_3D.shape)

torch.Size([2, 2, 2])


### Tensors Dimension and Tensor shape

`Tensor dimension:` The dimension of a tensor refers to the number of axes or indices needed to uniquely identify an element in the tensor. It describes the rank or order of the tensor.

`Tensor shape:` The shape of a tensor describes the size of each dimension. It tells you how many elements exist along each axis.


In [24]:
scalar.ndim

0

In [25]:
vector.ndim

1

In [26]:
MATRIX.ndim

2

In [31]:
TENSOR.ndim

2

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

### Random Tensors

`torch.rand()`

In [33]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3605, 0.2013, 0.9608, 0.0709],
         [0.6172, 0.5798, 0.5258, 0.0320],
         [0.3960, 0.9133, 0.7098, 0.9093]]),
 torch.float32)

### Zeros and Ones tensor

In [34]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(4, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [16]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:
* `start` = start of range (e.g. 0)
* `end` = end of range (e.g. 10)
* `step` = how many steps in between each valuethe future.

In [36]:
# Create a range of values 0 to 10
image = torch.arange(start=0, end=10, step=1)
image

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating tensor like

Sometimes you might want one tensor of a certain type with the same shape as another tensor.

For example, a tensor of all zeros with the same shape as a previous tensor. 

To do so you can use `torch.zeros_like(input)` or `torch.ones_like(input)` which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

In [37]:
# Creating a tensor of zero's similar any tensor of choice
ten_zeros = torch.zeros_like(input=image)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
# Creating a tensor of one's similar any tensor of choice
ten_zeros = torch.ones_like(image)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Precision in Machine Learning Engineering (Computer Science)

In computer science, **precision** refers to the level of detail or exactness with which a value is represented, particularly in numerical computations. It deals with how exact a representation or computation is, often in terms of the number of significant digits or bits used to represent data. The concept applies more broadly to any system that deals with data accuracy. 

`The base 10 -> base 2 analogy`

## Precision in Data representation

#### 1. **8-bit Precision**:
   - **Range**: If you're dealing with an 8-bit unsigned integer, it can represent values from `0` to `255` (i.e., \(2^8 = 256\) values). In the case of signed integers (which include negative numbers), the range is from `-128` to `127` for 8-bit integers.
   - **Application**: 8-bit precision is used in situations where minimal storage is needed, like grayscale pixel values (0–255) in images or basic integer operations in microcontrollers.

#### 2. **16-bit Precision**:
   - **Range**: For unsigned integers, 16 bits can represent values from `0` to `65,535` (i.e., \(2^{16} = 65,536\)). For signed integers, the range is from `-32,768` to `32,767`.
   - **Application**: This is common in older video games, audio processing, or where you need more precision but still want to limit memory usage. For floating-point numbers, 16-bit (half-precision) is often used in machine learning models to save memory and computational power.

#### 3. **32-bit Precision**:
   - **Range**: A 32-bit unsigned integer can represent values from `0` to `4,294,967,295` (i.e., \(2^{32} = 4,294,967,296\)). A signed 32-bit integer ranges from `-2,147,483,648` to `2,147,483,647`.
   - **Application**: 32-bit precision is common for general-purpose computing. In floating-point terms, a 32-bit float is called **single precision** and has about 7 significant decimal digits of precision. This is commonly used in scientific calculations and graphics.

#### 4. **64-bit Precision**:
   - **Range**: For unsigned integers, 64 bits can represent values from `0` to \(2^{64} - 1\), which is a very large number. Signed integers range from \(-2^{63}\) to \(2^{63} - 1\).
   - **Application**: 64-bit precision is used in modern systems for large data sets, scientific computing, and databases. In floating-point terms, **double precision** (64-bit) allows for about 15–16 significant decimal digits of precision, offering much higher accuracy for numerical computations.

## **Precision in Floating-Point Representation**:
The concept of precision becomes even more important in floating-point representations (such as IEEE-754 standard). These representations are split into a **mantissa** (significant digits) and **exponent** (magnitude), and the precision depends on how many bits are allocated to the mantissa.

#### 1. **Precision in Floating-Point Arithmetic:**
   - **Single Precision** (32-bit floating point): Typically uses 32 bits to represent a number, providing approximately 7 decimal digits of precision. This is the default precision in many systems and programming environments.
     - Example: `1.2345678` (7 significant digits)
   - **Double Precision** (64-bit floating point): Uses 64 bits, providing approximately 15–16 decimal digits of precision, allowing for much more accurate calculations compared to single precision.
     - Example: `1.23456789012345` (15 significant digits)
   - **Half Precision** (16-bit floating point): Uses 16 bits and provides about 3–4 decimal digits of precision. It is primarily used to save memory and computational power, often in deep learning models.
     - Example: `1.23` (3 significant digits)


### Summary:
- **Higher bit depths (16-bit, 32-bit, 64-bit, etc.)** offer **greater precision** because they allow more bits to represent the number, which provides a finer granularity of values.
- Precision determines the **range** and **accuracy** of the representation, meaning how small or large numbers can be, as well as how many significant digits can be captured.



### Creating Tensors with specific data type

This can come in handy for some kind of data manipulation.

In [12]:
float_tensor0 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(float_tensor)

tensor([1., 2., 3.], dtype=torch.float64)


In [10]:
float_tensor1 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
print(float_tensor1)

tensor([1., 2., 3.], dtype=torch.float16)


In [11]:
float_tensor2 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
print(float_tensor2)

tensor([1., 2., 3.], dtype=torch.float64)


## Tensor datatypes -> Precision : The consept of Precision is caption in ML as datatypes
#### Default datatype -> conversion from one datatype to anothern do so using the `dtype` parameter.

In [23]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # What device is your tensor on, CPU or GPU
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [24]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors (attributes)

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [13]:
float_tensor1.shape

torch.Size([3])

In [14]:
float_tensor2.dtype

torch.float64

In [25]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.8339, 0.0147, 0.6937, 0.5385],
        [0.2688, 0.3754, 0.4160, 0.2265],
        [0.3727, 0.4525, 0.2498, 0.0350]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).

### Basic operations

Let's start with a few of the fundamental operations, addition (`+`), subtraction (`-`), mutliplication (`*`).

They work just as you think they would.

In [26]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [28]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [29]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

### Subtraction

In [30]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [31]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [32]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix multiplication (Dot product)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html).



In [33]:
import torch

# Define two matrices (2D tensors)
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[5, 6], [7, 8]])

# Perform matrix multiplication using torch.matmul()
result = torch.matmul(matrix_a, matrix_b)
result

tensor([[19, 22],
        [43, 50]])

In [34]:
import torch

# Define two matrices (3x3 tensors)
matrix_a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Perform matrix multiplication using torch.matmul()
result = torch.matmul(matrix_a, matrix_b)
result

tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [35]:
import torch

# Define a 1x2 matrix and a 2x2 matrix
matrix_a = torch.tensor([[1, 2]])  # 1x2 matrix
matrix_b = torch.tensor([[3, 4], [5, 6]])  # 2x2 matrix

# Perform matrix multiplication
result = torch.matmul(matrix_a, matrix_b)
result

tensor([[13, 16]])

In [36]:
import torch

# Define two (3, 2) matrices
matrix_a = torch.tensor([[1, 2], [3, 4], [5, 6]])
matrix_b = torch.tensor([[7, 8], [9, 10], [11, 12]])

# Attempt to perform matrix multiplication
result = torch.matmul(matrix_a, matrix_b)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [37]:
import torch

# Define two (2, 3) matrices
matrix_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix_b = torch.tensor([[7, 8, 9], [10, 11, 12]])

# Attempt to perform matrix multiplication
result = torch.matmul(matrix_a, matrix_b)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

In [38]:
import torch

# Define a matrix (2D tensor)
matrix_a = torch.tensor([[1, 2], [3, 4]])

# Define a vector (1D tensor)
vector_b = torch.tensor([5, 6])

# Perform matrix-vector multiplication using torch.matmul()
result = torch.matmul(matrix_a, vector_b)
result

tensor([17, 39])

PyTorch implements matrix multiplication functionality in the [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) method.

The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`
3. Matrix to vector multiplication
 * `matrix (m x n)` * `vector n length` will work
     
   If you have a matrix \( A \) of shape \((m \times n)\) and a vector \( v \) of length \( n \), their matrix-vector multiplication results in a vector of length \( m \). Each element of the resulting vector is the dot product of a row of the matrix with the vector.
